create table if not exists public.app_telemetry (
  id bigint generated by default as identity primary key,
  install_id text not null check (length(install_id) <= 80),
  session_id text check (length(session_id) <= 80),
  event_kind text not null check (event_kind in ('analytics','crash')),
  event_name text not null check (length(event_name) <= 80),
  app_version text not null check (length(app_version) <= 20),
  route text check (length(route) <= 60),
  online boolean not null default true,
  occurred_at timestamptz not null,
  details jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

alter table public.app_telemetry enable row level security;

revoke all on table public.app_telemetry from anon, authenticated;
grant insert on table public.app_telemetry to anon, authenticated;
grant usage, select on sequence public.app_telemetry_id_seq to anon, authenticated;

create policy "clients can submit telemetry"
on public.app_telemetry for insert
to anon, authenticated
with check (
  event_kind in ('analytics','crash')
  and octet_length(details::text) <= 4096
);

create index if not exists app_telemetry_received_at_idx on public.app_telemetry(received_at desc);
create index if not exists app_telemetry_event_idx on public.app_telemetry(event_kind,event_name,received_at desc);

comment on table public.app_telemetry is 'Sanitized operational analytics and crash reports. No names, contact details, medical content, messages, financial values, or precise location.';
